Repository khusnetdinov/betterdocs, pull requests merged in 2018-11, with the labels that each got.

#89 Added robots.txt
  Gemfile
  Gemfile.lock
  _config.yml
  robots.txt
Labels: Ready, blocked-by-other

#90 Urgent update jekull
  Gemfile
  Gemfile.lock
Labels: Ready

#93 [#66] contribution guides
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: Ready

#94 [#70] Codetriage badge
  README.md
Labels: Ready

#92 [#75] Fixed problems on site with HTML
  _includes/counters.html
  _includes/head.html
  _includes/header.html
  _layouts/default.html
  _pages/index.html
  _sass/_base.scss
Labels: Ready

#95 [#13] Sponsor blocks
  _includes/sidebar.html
  _includes/sponsors/234x60.html
  _includes/sponsors/300x600.html
  _includes/sponsors/468x60.html
  _includes/sponsors/728x90.html
  _pages/algorithms.html
  _pages/data_structures.html
  _pages/design_patterns.html
  _pages/functional_programming.html
  _pages/gotchas.html
  _pages/index.html
  _pages/interview_questions.html
  _pages/meta_programming.html
  _pages/solid_principles.html
  _pages/threads.html
  _sass/_base.scss
  _sass/_main.scss
  _sass/_sponsors.scss
  css/main.scss
Labels: Ready

#96 [#13][Hotfix] Hide sponsor blocks
  _sass/_sponsors.scss
Labels: bug

#99 [#61] Ruby Master books
  _i18n/en.yml
  _includes/sponsors/234x60.html
  _pages/ruby_meister.html
  _sass/_base.scss
  _sass/_layout.scss
  _sass/_sponsors.scss
  images/en/books/algorithm_manual.jpg
  images/en/books/c_lang.jpg
  images/en/books/code.jpg
  images/en/books/compilers.jpg
  images/en/books/concrete_math.jpg
  images/en/books/cormen.jpg
  images/en/books/design_programms.jpg
  images/en/books/domain_driven.jpg
  images/en/books/growing.jpg
  images/en/books/inside_machine.jpg
  images/en/books/programming_ruby.jpg
  images/en/books/ruby_programming.jpg
  images/en/books/sicp.jpg
  images/en/books/well_grounded.jpg
  images/loading.svg
Labels: Ready

#101 [#62] Interview links
  _i18n/en.yml
  _pages/interview_questions.html
Labels: Ready

#102 [#62] Index page
  _i18n/en.yml
  _includes/github.html
  _includes/head.html
  _pages/algorithms.html
  _pages/data_structures.html
  _pages/design_patterns.html
  _pages/functional_programming.html
  _pages/gotchas.html
  _pages/index.html
  _pages/interview_questions.html
  _pages/meta_programming.html
  _pages/ruby_meister.html
  _pages/solid_principles.html
  _pages/threads.html
  _sass/_base.scss
Labels: Ready

#103 [#100] Typos
  _i18n/en.yml
  _pages/design_patterns.html
Labels: Ready

#108 [#101] Refactor and add submenus
  _i18n/en.yml
  _includes/head.html
  _includes/header.html
  _includes/javascripts.html
  _includes/sidebar.html
  _layouts/default.html
  _layouts/page.html
  _pages/404.html
  _pages/algorithms.html
  _pages/data_structures.html
  _pages/design_patterns.html
  _pages/functional_programming.html
  _pages/gotchas.html
  _pages/index.html
  _pages/interview_questions.html
  _pages/meta_programming.html
  _pages/ruby_meister.html
  _pages/solid_principles.html
  _pages/threads.html
  _plugins/revision_generator.rb
  _sass/_base.scss
  _sass/_layout.scss
  _sass/_sponsors.scss
  javascripts/main.js
  javascripts/vendor/classie.js
  javascripts/vendor/dummydata.js
Labels: Ready

#109 [#107] Add envs
  Procfile
  _config.production.yml
  _config.staging.yml
  _config.yml
  _includes/head.html
  _includes/header.html
  robots.txt
  sitemap.xml
Labels: Ready

#114 [#71] Sitemap
  404.html
  _config.staging.yml
  _layouts/404.html
  _pages/algorithms.html
  _pages/data_structures.html
  _pages/design_patterns.html
  _pages/functional_programming.html
  _pages/gotchas.html
  _pages/index.html
  _pages/interview_questions.html
  _pages/meta_programming.html
  _pages/ruby_meister.html
  _pages/solid_principles.html
  _pages/threads.html
  robots.txt
  sitemap.xml
Labels: Ready
